logLevel: info

api: yes
apiAddress: :9997

rtmp: yes
rtmpAddress: :1935

hls: yes
hlsAddress: :8080


webrtc: yes
webrtcAddress: :8889
webrtcICEServers2: []

paths:
  all:
    source: publisher
    record: yes
    # Chemin DANS le conteneur où MediaMTX va écrire les fichiers.
    # %path sera remplacé par 'all'.
    # %Y%m%d_%H%M%S assure un nom de fichier unique par session.
    recordPath: /project_recordings/%path/%Y%m%d_%H%M%S
    recordFormat: fmp4
